-Added denoising support via OIDN (both final images and previews) -Turned off min_variance by default -Switched matrix class to be full RGB packaged floats and added channel member

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -618,6 +618,9 @@ LIBOBJS
 DEFINES
 PKG_LIBS
 PKG_CPPFLAGS
+OIDN_LIBS
+OIDN_LDFLAGS
+OIDN_CPPFLAGS
 CXXCPP
 XMKMF
 ac_ct_CXX
@@ -4408,6 +4411,36 @@ else
   fi
 fi
 
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Open Image Denoise (OIDN)" >&5
+printf %s "checking for Open Image Denoise (OIDN)... " >&6; }
+
+OIDN_CPPFLAGS=""
+OIDN_LDFLAGS=""
+OIDN_LIBS=""
+
+if test -d "$OIDN_PATH"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: found at $OIDN_PATH" >&5
+printf "%s\n" "found at $OIDN_PATH" >&6; }
+  OIDN_CPPFLAGS="-I$OIDN_PATH/include"
+  OIDN_LDFLAGS="-L$OIDN_PATH/lib"
+  OIDN_LIBS="-lOpenImageDenoise -ltbb"
+  DEFINES="${DEFINES} -DHAS_OIDN"
+  # If we are on Darwin (macOS), add the rpath entry
+  if test $darwin = yes; then
+    OIDN_LDFLAGS="${OIDN_LDFLAGS} -Wl,-rpath,$OIDN_PATH/lib"
+  fi
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: OIDN not found. Skipping OIDN support." >&5
+printf "%s\n" "$as_me: WARNING: OIDN not found. Skipping OIDN support." >&2;}
+  OIDN_CPPFLAGS=""
+  OIDN_LDFLAGS=""
+  OIDN_LIBS=""
+fi
+
+
+
+
+
 # Check for SSE2 support first
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SSE2 support" >&5
 printf %s "checking for SSE2 support... " >&6; }
@@ -4488,9 +4521,9 @@ printf "%s\n" "no" >&6; }
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
 
-PKG_CPPFLAGS="${PKG_CPPFLAGS}"
+PKG_CPPFLAGS="${PKG_CPPFLAGS} ${OIDN_CPPFLAGS}"
 
-PKG_LIBS="${LIBS} ${PKG_LIBS}"
+PKG_LIBS="${LIBS} ${PKG_LIBS} ${OIDN_LDFLAGS} ${OIDN_LIBS}"
 
 DEFINES="${DEFINES}"
 
